---
platform: ios

creds_core_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  timeout: 60

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  dev_os: "ios"
  optional_args: {}
