---
- name: Exercise2
  hosts: nxos
  tasks:

    - name: Configure IPv4 interfaces
      nxos_l3_interface:
        provider: "{{ provider_ssh }}"
        name: "{{ item.name }}"
        ipv4: "{{ item.addr }}/{{ item.mask }}"
      with_items: "{{ ip_interfaces }}"
      when: "item.type == 'v4'"
      notify: write mem

    - name: Configure IPv6 interfaces
      nxos_l3_interface:
        provider: "{{ provider_ssh }}"
        name: "{{ item.name }}"
        ipv6: "{{ item.addr }}/{{ item.mask }}"
      with_items: "{{ ip_interfaces }}"
      when: "item.type == 'v6'"
      notify: write mem

  handlers:
    - name: write mem
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
      changed_when: True
